covidapp/urls.py
from django.contrib import admin
from django.urls import path


from covidapp.views import hospital_create_view, hospital_detail_view, hospital_list_view, hospital_index_view, hospital_chart_view
from covidapp import views

app_name = 'covidapp'

urlpatterns = [
	path('createCovid', hospital_create_view),
	path('', views.hospital_index_view, name='hospital-index'),
	path('hospitals/', views.hospital_list_view, name='hospital-list'),
	path('<int:id>/', views.hospital_detail_view, name='hospital-detail'),
	path('hospital_chart_view', views.hospital_chart_view, name='hospital_chart_view')
	#path('<int:id>/', hospital_detail_view),
	#path('product', product_detail_view, name='product-detail'),
    # path('create', product_create_view),
    # path('', product_list_view, name='product-list'),
    
    # path('initial', render_initial_data),
    # #path('<int:id>/', dynamic_lookup_view, name='product-detail'),
    # path('<int:id>/delete/', product_delete_view, name='product-delete'),
]

trydjango207/urls.py
from django.contrib import admin
from django.urls import include,path
from covidapp import views
#from django.views.generic import RedirectView
from covidapp.views import hospital_create_view, hospital_detail_view, hospital_list_view, hospital_index_view

urlpatterns = [
    path('createCovid', hospital_create_view),
    #path('covidapp/', hospital_list_view, name='hospital-list'),
    #path('', RedirectView.as_view(url='covidapp/', permanent=True)),
    path('covidapp/', include('covidapp.urls')),
    #path('oneCovid/', hospital_detail_view, name='product-delete'),
    #path('oneCovid/<int:id>/', hospital_detail_view, name='product-detail'),
    #path('blog/', include('blog.urls')),
    #path('products/', include('products.urls')),
    #path('', home_view, name='home'),
    #path('contact/', contact_view),
    #path("", include('covidapp.urls')),
    #path('<int:id>/', product_detail_view, name='product-detail'),
    #path('product/', product_detail_view, name='product-detail'),
    #path('create/', product_create_view, name='product-create'),
    #path('products/', product_list_view, name='product-list'),
    path('admin/', admin.site.urls),
    #path('about/', about_view),
    #path('initial', render_initial_data),
    #path('products/<int:id>/', dynamic_lookup_view, name='product-detail'),
    #path('products/<int:id>/delete/', product_delete_view, name='product-delete'),
    #path('pageview/', my_page_view, name='page-view')
]

covidapp/models.py
from django.db import models
from django.urls import reverse
import datetime

# Create your models here.

class Hospital(models.Model):
    date_time 			=    	models.DateField()
    hospital_currently 	= 		models.IntegerField(blank=True, null=True)
    icucurrently		= 		models.IntegerField(blank=True, null=True)
    hospital_increase 	= 		models.IntegerField(blank=True, null=True)
    dead_daily			= 		models.IntegerField(blank=True, null=True)
    tested_today		=		models.IntegerField(blank=True, null=True)


    def get_absolute_url(self):
    	return reverse("hospital-list", kwargs={"id": self.id}) 

covidapp/forms.py
from django import forms
import datetime
from .models import Hospital


class HospitalForm(forms.ModelForm):
	date_time   			= forms.DateField(initial=datetime.date.today)
	hospital_currently 		= forms.IntegerField(required=False)
						# 			required=False, 
						# 			widget=forms.Textarea(
						# 		  	attrs={
						# 		  		"cols": 20, "rows":5,
						# 		  		"placeholder": "your description",
						# 		  		"class": "new-class-name two",
						# 		  		"id": "my-id-for-textarea",
						# 		  		# "rows": 20,
						# 		  		# "cols": 26,
						# 		  	}
						# 	)
						# )
	icucurrently   			= forms.IntegerField(required=False)
	hospital_increase       = forms.IntegerField(required=False)
	dead_daily				= forms.IntegerField(required=False)
	tested_today			= forms.IntegerField(required=False)

	class Meta:
		model = Hospital
		fields = [
			'date_time',
			'hospital_currently',
			'icucurrently',
			'hospital_increase',
			'dead_daily',
			'tested_today',
		]

covidapp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import Http404

from django.shortcuts import render, get_object_or_404, redirect

from .forms import HospitalForm

# Create your views here.
from .models import Hospital
from chartit import DataPool, Chart

def hospital_create_view(request):
	form = HospitalForm(request.POST or None)
	if form.is_valid():
		form.save()
		form = HospitalForm()
	# context = {
	# 	'title': obj.title,
	# 	'description': obj.description
	# }
	context = {
		'form': form
	}
	return render(request, "covidapp/hospital_create.html", context) 


def hospital_detail_view(request, id):
	obj = Hospital.objects.get(id=id)
	
	# context = {
	# 	'hospitalCurrently': obj.hospital_currently,
	# 	'deadDaily': obj.dead_daily,
	# 	'hospitalIncrease': obj.hospital_increase,
	# 	'ICUincrease': obj.ICU_currently,
	# }
	# try:
	# 	obj = Hospital.objects.get(id=id)
	# except Hospital.DoesNotExist:
	# 	raise Http404
	context = {
		"object": obj
	}
	return render(request, "covidapp/hospital_detail.html", context)

def hospital_list_view(request):
	queryset = Hospital.objects.all() #list of objects 
	num_hospital = Hospital.objects.all().count()
	context = {
		"object_list": queryset, 
		"num_hospital": num_hospital,  
		#'hospitalCurrently': queryset,
    	# 'num_instances': num_instances,
    	# 'num_instances_available': num_instances_available,
    	# 'num_authors': num_authors,   # object_list is the key and queryset is the value
	}
	return render(request, "covidapp/hospital_list.html", context)

def hospital_index_view(request):
	
	num_hospital = Hospital.objects.all().count()
	context = {
		
		"num_hospital": num_hospital,  
		#'hospitalCurrently': queryset,
    	# 'num_instances': num_instances,
    	# 'num_instances_available': num_instances_available,
    	# 'num_authors': num_authors,   # object_list is the key and queryset is the value
	}
	return render(request, "covidapp/hospital_index.html", context)


# def dynamic_lookup_view(request, id):
# 	#obj = Product.objects.get(id=id)
# 	#obj = get_object_or_404(Product, id=id)
# 	try:
# 		obj = Product.objects.get(id=id)
# 	except Product.DoesNotExist:
# 		raise Http404
# 	context = {
# 		"object": obj
# 	}
# 	return render(request, "products/product_detail.html", context)

def hospital_chart_view(request):
    #Step 1: Create a DataPool with the data we want to retrieve.
    #Step 1: Create a DataPool with the data we want to retrieve.
    hospitaldata = \
        DataPool(
           series=
            [{'options': {
              'source': Hospital.objects.all()},
              'terms': [{'date_time': 'date_time', 'tested_today': 'tested_today'}]
               }
             ])


    #Step 2: Create the Chart object
    cht = Chart(
            datasource = hospitaldata,
            series_options =
              [{'options':{
                  'type': 'column',
                  'stacking': False},
                'terms':{
                  'date_time': [
                    
                    'tested_today']
                    
                    
                     
                  
                  }}],
            chart_options =
              {'title': {
                   'text': 'hospital data'},
               'xAxis': {
                    'title': {
                       'text': 'days selected'}}})
	


    #Step 3: Send the chart object to the template.
    return render(request, 'hospitalchart.html', {'chart_list': [cht]})

covidapp/templates/covidapp/hospital_create.html
{% extends 'base.html' %}

{% block content %}
<form action='' method='POST' novalidate>{% csrf_token %}
	
	{{ form.as_p }}
	<input type='submit' value='Save' />

</form>

{% endblock %}

covidapp/templates/covidapp/hospital_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


<h1>{% block header %}Covid-19 data for NY State: </h1>{% endblock %}
<h2>{% block title %}This is the data you requested: </h2>{{ object.date_time }}{% endblock %}

<h4>Patients in hospitals: </h4> {{ object.hospital_currently }}

<h4>Patients in ICU: </h4>{{ object.icu_currently }}

<h4>Hospitalized patients increase today: </h4>{{ object.hospital_increase }}

<h4>Death increase today: </h4>{{ object.dead_daily }}

<h4>Patients tested today: </h4>{{ object.tested_today }}

{% endblock %}

{% block sidebar %}


{% endblock %}

covidapp/templates/covidapp/hospital_index.html
{% extends 'base.html' %}

{% block content %}




  <h1>Covid-19 NY State Data</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>


  	



  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Entries:</strong> {{ num_hospital }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>



  <!-- {% for instance in object_list %}
  <p>{{ instance.id }} - <a href='{{ instance.get_absolute_url }}'>{{ instance.dead_daily }}</p>
  <p>{{ instance.tested_today }} - <a href='{{ instance.get_absolute_url }}'>test- <a href="{% url 'hospital-list' %}">mamadera</a>{{ instance.dead_daily }}</p>
  {% endfor %} -->
  
{% endblock %}

covidapp/templates/covidapp/hospital_list.html
{% extends 'base.html' %}

{% block content %}
<h3> Pick on a date to view the data </h3>

<div class="container">
    <div class="row">
    </div>


      {% for instance in object_list %}
      <p><a class="btn btn-light" href='/covidapp/{{ instance.id }}'>{{ instance.date_time }}</a></p>
      {% endfor %}
      <a href="/covidapp/hospitals" class="btn btn-success btn-sm"><i aria-hidden="true" class="fa fa-line-chart"></i> See graph</a>


      {% endblock %}
    </div>
      
    


    
</div>

covidapp/templates/covidapp/hospitalchart.html
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- jQuery CDN -->
    <script
    src="https://code.jquery.com/jquery-1.12.4.min.js"
    integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
    crossorigin="anonymous"></script>
     <!-- highcharts CDN -->
    <script src="https://code.highcharts.com/highcharts.src.js"></script>

    {% load chartit %}
    {{ chart_list|load_charts:"cht" }}
</head>
<body>
    <div id='cht'>  </div>
 
</body>
</html>

covidapp/templates/hospitalchart.html
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- jQuery CDN -->
    <script
    src="https://code.jquery.com/jquery-1.12.4.min.js"
    integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
    crossorigin="anonymous"></script>
     <!-- highcharts CDN -->
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
   
    {% load chartit %}
    {{ chart_list|load_charts:"cht" }}
</head>
<body>
    <div id="cht"></div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  

 
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div id='cht'></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a class="btn btn-primary" href="{% url 'covidapp:hospital-list' %}">All hospital entries</a></li>
        </ul>
      {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
</body>
</html>